name = "Ian McCrystal"
domain = "ianmccrystal.com"
url = "https://ianmccrystal.com"
description = "A quiet personal website for writing, notes, and projects."
footer ="It's the job that's never started as takes longest to finish."
